name: "Build PDF"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    steps:
      - name: Install pygmentize
        run: apt update && apt install -y python3-pygments
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build PDF
        run: latexmk ./formulary.tex -shell-escape
      - name: Commit PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Build PDF'
          commit_author: 'Actions Bot <actions@github.com>'
