name: "Build PDF"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install git and pygmentize
        run: |
          sudo apt update
          sudo apt install -y python3-pygments git texlive-full
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build PDF
        run: |
          set +e
          pdflatex -shell-escape -interaction=nonstopmode ./formulary.tex
          if [ -f formulary.pdf ]; then 
            exit 0 
          else 
            exit 1 
          fi 
      - name: Commit PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Build PDF'
          commit_author: 'Actions Bot <actions@github.com>'
